### ISSUE TITLE
prior steps increasing makes images randomly changed from the same seed

### ISSUE THREAD

**Issue by ptits** [EtienneDosSantos/stable-cascade-one-click-installer#16]
I use the same seed. 
But prior_steps 20, 30, 40 gave me very different images (for the same decoder steps or for 10,15,20)

Here - https://huggingface.co/spaces/multimodalart/stable-cascade - I have now such a difference - they are the same

Trey to increase prior_steps and compare images

**Comment by EtienneDosSantos** [comment]
> I use the same seed.
> But prior_steps 20, 30, 40 gave me very different images (for the same decoder steps or for 10,15,20)

I think, for Stable Cascade applies as previously for SD 1.5 and SDXL: changing step count, changes generated image, even if seed is locked.

> Here - https://huggingface.co/spaces/multimodalart/stable-cascade - I have now such a difference - they are the same

Looks like the prior steps slider is broken. Makes no sense that 10 step prior and 30 step prior look the same.

**Comment by ptits** [comment]
> Looks like the prior steps slider is broken. Makes no sense that 10 step prior and 30 step prior look the same.
Yes, they do have broken prior steps. I tried local version - the same error.
