### ISSUE TITLE
MacBook Pro M3 Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Sludge2158** [EtienneDosSantos/stable-cascade-one-click-installer#23]
Hi,

I'm facing a problem running it on my MacBook. It shows an error "Torch not compiled with CUDA enabled" but MacOS doesn't support CUDA. I have PyTorch 2.2.1 which should work with CPU. Can you help fix this?

stable-cascade-one-click-installer-main/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by EtienneDosSantos** [comment]
1. `pip uninstall torch`
2. `pip3 install torch torchvision`

This shoud hopefully resolve the issue. Let me know, if it doesn't.

**Comment by PierrunoYT** [comment]
https://www.perplexity.ai/search/Hi-Im-facing-fQfzxovuQZ6.1ra_sxj63w#0
