### ISSUE TITLE
Insightface errors on install

### ISSUE THREAD

**Issue by Eamead** [EtienneDosSantos/stable-cascade-one-click-installer#6]
Can't actually install this project. I have python 3.10.6 installed on my machine, but i keep running into some kind of error with insight face. I'll grant I don't use python much, so it could be user error. But this is a clean install on windows with a clean install of python. Not sure how I could really mess it up.

Attached Error output for your reading pleasure.
[Error.txt](https://github.com/EtienneDosSantos/stable-cascade-one-click-installer/files/14290056/Error.txt)

**Comment by Eamead** [comment]
Well, it was an inexperience issue, and what seems to be a documentation issue. It turns out that this project requires both python _and_ Visual Studio build tools for Desktop development for C++. You need to update your installation instructions.

**Comment by EtienneDosSantos** [comment]
Thank you, added in [`commit bd1c851`](https://github.com/EtienneDosSantos/stable-cascade-one-click-installer/commit/bd1c8515244a3d970b264d34f38d48596155282e).
